algoritmo "semnome"

var
   m1:vetor[1..3,1..4] de inteiro
   linha, coluna:inteiro
inicio

      para linha de 1 ate 3 faca
          para coluna de 1 ate 4 faca
            escreva("Informe o número: ")
            leia(m1[linha,coluna])
          fimpara
      fimpara
      
      para linha de 1 ate 3 faca
          para coluna de 1 ate 4 faca
            escreva(m1[linha,coluna])
          fimpara
          escreval()
      fimpara
      


fimalgoritmo
